title: Cheatsheets
author: TAKEUCHI Hitoshi
description: チートシートを置いてます。<a href="https://github.com/htakeuchi/cheatsheet/">Markdownからチートシートを生成する自作ツール</a>を使っています。
home: https://cheatsheets.namaraii.com/

links:
  site:
    url: https://namaraii.com/
    title: namaraii.com
  email: hitoshi@namaraii.com
  bluesky: https://bsky.app/profile/namaraii.com
  mastodon: https://fedibird.com/@htakeuchi
  threads: https://www.threads.net/@htakeuchi
  github: https://github.com/htakeuchi
